<a href="https://colab.research.google.com/github/BillyMuthiani/DATA-SCIENCE-REPOSITORY/blob/main/Numpy_Essentials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
grades=np.array([85,90,88,92,95,80,75,98,89,83])

In [4]:
mean=np.mean(grades)
median=np.median(grades)
std_dev=np.std(grades)
print("Mean:",mean)
print("Median:",median)
print("Standard Deviation:",std_dev)

Mean: 87.5
Median: 88.5
Standard Deviation: 6.591661399070799


In [5]:
max=np.max(grades)
min=np.min(grades)
print("maximum:",max)
print("minimum:",min)

maximum: 98
minimum: 75


In [6]:
sort=np.sort(grades)
print(sort)

[75 80 83 85 88 89 90 92 95 98]


In [7]:
index=np.argmax(grades)
print(grades[index])

98


In [8]:

print(grades[grades>90])

[92 95 98]


In [9]:
print(np.mean(grades>90)*100)

30.0


In [10]:
print(np.mean(grades<75)*100)

0.0


In [14]:
print(grades)


[85 90 88 92 95 80 75 98 89 83]


In [17]:
high_performers =grades[grades>90]
print("high_performers:", high_performers)


high_performers: [92 95 98]


In [18]:
passing_grades = grades[grades>75]
print("passing_grades:",passing_grades)

passing_grades: [85 90 88 92 95 80 98 89 83]
